# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

variables:
  - group: port-credentials
  - group: synk-credentials


steps:
- task: Docker@2
- script: |
    echo Add other tasks to build, test, and deploy your project.
    # Set Docker image and run the container
    integration_type="snyk"
    version="latest"

    image_name="ghcr.io/port-labs/port-ocean-$integration_type:$version"

    docker run -i --rm --platform=linux/amd64 \
    -e OCEAN__EVENT_LISTENER='{"type":"ONCE"}' \
    -e OCEAN__INITIALIZE_PORT_RESOURCES=true \
    -e OCEAN__INTEGRATION__CONFIG__TOKEN=${SYNK_TOKEN} \
    -e OCEAN__PORT__CLIENT_ID=${PORT_CLIENT_ID} \
    -e OCEAN__PORT__CLIENT_SECRET=${PORT_CLIENT_SECRET} \
    $image_name

    exit $?
  displayName: 'Ingest Synk Data into Port'
