# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: port-credentials


steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    # Set Docker image and run the container
    integration_type="snyk"
    version="latest"

    image_name="ghcr.io/port-labs/port-ocean-$integration_type:$version"

    docker run -i --rm --platform=linux/amd64 \
    -e OCEAN__EVENT_LISTENER='{"type":"ONCE"}' \
    -e OCEAN__INITIALIZE_PORT_RESOURCES=true \
    -e OCEAN__INTEGRATION__CONFIG__TOKEN=${{ OCEAN__INTEGRATION__CONFIG__TOKEN }} \
    -e OCEAN__PORT__CLIENT_ID=${{ OCEAN__PORT__CLIENT_ID }} \
    -e OCEAN__PORT__CLIENT_SECRET=${{ OCEAN__PORT__CLIENT_SECRET }} \
    $image_name

    exit $?
  displayName: 'Ingest Synk Data into Port'
