apiVersion: apps/v1
kind: Deployment
metadata:
  name: bard
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bard
  template:
    metadata:
      labels:
        app: bard
    spec:
      containers:
        - image: new-image-name:latest
          name: bard
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
