# s3bucket-crossplane.yaml

apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ bucket_name }}
spec:
  forProvider:
    region: {{ aws_region }}
  providerConfigRef:
    name: default