name: Create Statuspage Incident and Notify Port

on:
  workflow_dispatch:
    inputs:
      incident_title:
        description: "Title of the incident"
        required: true
      incident_message:
        description: "Description of the incident"
        required: true
      incident_severity:
        description: "Severity: none, minor, major, critical"
        required: true
        type: choice
        options:
          - none
          - minor
          - major
          - critical
      incident_status:
        description: "Status: investigating, identified, monitoring, resolved"
        required: true
        type: choice
        options:
          - investigating
          - identified
          - monitoring
          - resolved
      status_page:
        description: "Statuspage page ID"
        required: false
      affected_components:
        description: "List of components affected by the incident"
        required: false
      port_context: # Input for Port context (JSON)
        description: "Port context (JSON format)"
        required: true

# If Ocean is enabled, the STATUSPAGE_PAGE_ID will be set in the context 
# since the self service action is created against the Statuspage entity
env:
  STATUSPAGE_PAGE_ID: ${{ inputs.status_page || secrets.STATUSPAGE_PAGE_ID }}


jobs:
  create_statuspage_incident:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Port (Initial)
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Creating Statuspage incident: ${{ inputs.incident_title }}

      - name: Create Statuspage Incident
        id: create_incident
        run: |
          echo "Creating Statuspage incident: ${{ inputs.incident_title }} in status page: ${{ env.STATUSPAGE_PAGE_ID }}"
          
          payload='{
              "incident": {
                "name": "${{ inputs.incident_title }}",
                "body": "${{ inputs.incident_message }}",
                "status": "${{ inputs.incident_status }}",
                "impact_override": "${{ inputs.incident_severity }}",
                "deliver_notifications": true,
                "component_ids": ${{ inputs.affected_components }},
                "metadata": {
                  "port": {
                    "runId": "${{ fromJson(inputs.port_context).runId }}",
                    "triggeredBy": "${{ fromJson(inputs.port_context).trigger.by.user.email }}"
                  }
                }
              }
            }'
          
          # Add scheduled fields only if the incident is scheduled
          if [[ "${{ inputs.incident_status }}" =~ ^(scheduled|in_progress|verifying|completed)$ ]]; then
            # Calculate default start and end times for scheduled maintenance (next hour, 3 hours duration)
            start_time=$(date -u -d "+1 hour" +%Y-%m-%dT%H:%M:%S.000Z)
            end_time=$(date -u -d "+4 hours" +%Y-%m-%dT%H:%M:%S.000Z)

            payload=$(echo "$payload" | jq --arg start_time "$start_time" --arg end_time "$end_time" '.incident += {"scheduled_for": $start_time, "scheduled_until": $end_time, "scheduled_remind_prior": true, "scheduled_auto_in_progress": true, "scheduled_auto_completed": true}')
          fi
          
          echo "$payload"

          response=$(curl -s -X POST "https://api.statuspage.io/v1/pages/${{ env.STATUSPAGE_PAGE_ID }}/incidents" \
            -H "Authorization: OAuth ${{ secrets.STATUSPAGE_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$payload")

          echo "$response"
          echo "INCIDENT=$response" >> $GITHUB_ENV
          echo "$response" > response.json

          echo "incident_id=$(jq -r '.id' response.json)" >> $GITHUB_OUTPUT
          echo "name=$(jq -r '.name' response.json)" >> $GITHUB_OUTPUT
          echo "status=$(jq -r '.status' response.json)" >> $GITHUB_OUTPUT
          echo "impact=$(jq -r '.impact' response.json)" >> $GITHUB_OUTPUT
          echo "created_at=$(jq -r '.created_at' response.json)" >> $GITHUB_OUTPUT
          echo "updated_at=$(jq -r '.updated_at' response.json)" >> $GITHUB_OUTPUT
          echo "started_at=$(jq -r '.started_at' response.json)" >> $GITHUB_OUTPUT
          echo "resolved_at=$(jq -r '.resolved_at' response.json)" >> $GITHUB_OUTPUT
          echo "scheduled_until=$(jq -r '.scheduled_until' response.json)" >> $GITHUB_OUTPUT
          echo "scheduled_for=$(jq -r '.scheduled_for' response.json)" >> $GITHUB_OUTPUT
          echo "scheduled_auto_in_progress=$(jq -r '.scheduled_auto_in_progress' response.json)" >> $GITHUB_OUTPUT
          echo "scheduled_auto_completed=$(jq -r '.scheduled_auto_completed' response.json)" >> $GITHUB_OUTPUT
          echo "scheduled_remind_prior=$(jq -r '.scheduled_remind_prior' response.json)" >> $GITHUB_OUTPUT
          echo "scheduled_reminded_at=$(jq -r '.scheduled_reminded_at' response.json)" >> $GITHUB_OUTPUT
          echo "metadata=$(jq -r '.metadata' response.json)" >> $GITHUB_OUTPUT
          echo "reminder_intervals=$(jq -r '.reminder_intervals' response.json)" >> $GITHUB_OUTPUT



          
      - name: Print Incident
        env:
          incident: ${{ steps.create_incident.outputs.INCIDENT }}
          INCIDENT_ID: ${{ steps.create_incident.outputs.incident_id }}
          STATUS: ${{ steps.create_incident.outputs.status }}
        run: |
          echo "Incident ID: ${{ env.INCIDENT_ID }}"
          echo "Incident Status: ${{ env.STATUS }}"
          echo "Incident: ${{ fromJson(env.incident).id }}"
          
      
      - name: Upsert Entity in Port
        uses: port-labs/port-github-action@v1
        env:
          INCIDENT_ID: ${{ steps.create_incident.outputs.incident_id }}
          STATUS: ${{ steps.create_incident.outputs.status }}
          IMPACT: ${{ steps.create_incident.outputs.impact }}
          CREATED_AT: ${{ steps.create_incident.outputs.created_at }}
          UPDATED_AT: ${{ steps.create_incident.outputs.updated_at }}
          STARTED_AT: ${{ steps.create_incident.outputs.started_at }}
          RESOLVED_AT: ${{ steps.create_incident.outputs.resolved_at }}
          SCHEDULED_UNTIL: ${{ steps.create_incident.outputs.scheduled_until }}
          SCHEDULED_FOR: ${{ steps.create_incident.outputs.scheduled_for }}
          SCHEDULED_AUTO_IN_PROGRESS: ${{ steps.create_incident.outputs.scheduled_auto_in_progress }}
          SCHEDULED_AUTO_COMPLETED: ${{ steps.create_incident.outputs.scheduled_auto_completed }}
          SCHEDULED_REMIND_PRIOR: ${{ steps.create_incident.outputs.scheduled_remind_prior }}
          SCHEDULED_REMINDED_AT: ${{ steps.create_incident.outputs.scheduled_reminded_at }}
          METADATA: ${{ steps.create_incident.outputs.metadata }}
          REMINDER_INTERVALS: ${{ steps.create_incident.outputs.reminder_intervals }}

        with:
          identifier: ${{ env.INCIDENT_ID }}
          title: ${{ inputs.incident_title }}
          team: "[]"
          icon: DefaultBlueprint
          blueprint: ${{ fromJson(inputs.port_context).blueprint }}
          properties: |-
            {
              "impact": "${{ env.IMPACT }}",
              "status": "${{ env.STATUS }}",
              "createdAt": "${{ env.CREATED_AT }}",
              "updatedAt": "${{ env.UPDATED_AT }}",
              "startedAt": "${{ env.STARTED_AT }}",
              "resolvedAt": "${{ env.RESOLVED_AT }}",
              "scheduled_until": "${{ env.SCHEDULED_UNTIL }}",
              "scheduled_for": "${{ env.SCHEDULED_FOR }}",
              "scheduled_auto_in_progress": "${{ env.SCHEDULED_AUTO_IN_PROGRESS }}",
              "scheduled_auto_completed": "${{ env.SCHEDULED_AUTO_COMPLETED }}",
              "scheduled_remind_prior": "${{ env.SCHEDULED_REMIND_PRIOR }}",
              "scheduled_reminded_at": "${{ env.SCHEDULED_REMINDED_AT }}",
              "metadata": "${{ env.METADATA }}",
              "reminder_intervals": "${{ env.REMINDER_INTERVALS }}",
              "pageId": "${{ env.STATUSPAGE_PAGE_ID }}",
              "component_ids": "${{ inputs.affected_components }}"
            }
          relations: |-
            {
              "statuspage": "${{ env.STATUSPAGE_PAGE_ID }}"
            }
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          runId: ${{ fromJson(inputs.port_context).runId }}
      

      - name: Notify Port (Initial)
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          status: "SUCCESS"
          logMessage: |
            Finished creating Statuspage incident: ${{ inputs.incident_title }}
