name: Create New S3 Bucket Crossplane Manifest

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: "Name of the s3 bucket"
        required: true
      aws_region:
        description: "AWS Region for the cluster"
        required: true
      port_payload:
        required: true
        description: >-
          Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Inform execution of request to create a new manifest
        id: promote
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
          logMessage: "About to create a crossplane manifest for a new s3 bucket..."

      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Create crossplane manifest for s3 bucket
      #   id: create-manifest
      #   env:
      #     BUCKET_FILE_PATH: "manifests/s3bucket"
      #     CROSSPLANE_TEMPLATE_PATH: "crossplane-templates/s3bucket-crossplane.yaml"
      #   run: |
      #     mkdir -p $BUCKET_FILE_PATH
      #     BUCKET_FILE_NAME="${BUCKET_FILE_PATH}/s3bucket-${{ fromJson(inputs.bucket_name) }}.yaml"

      #     cp $CROSSPLANE_TEMPLATE_PATH $BUCKET_FILE_NAME

      #     sed -i "s/{{ bucket_name }}/${{ fromJson(inputs.bucket_name) }}/g" $BUCKET_FILE_NAME
      #     sed -i "s/{{ aws_region }}/${{ fromJson(inputs.aws_region) }}/g" $BUCKET_FILE_NAME

      #     git add $BUCKET_FILE_NAME
            
      # - name: Create Pull Request
      #   id: create-pr
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.CREATOR_TOKEN }}
      #     commit-message: Added ${{ fromJson(inputs.bucket_name) }} s3 bucket crossplane manifest
      #     committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      #     author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
      #     signoff: false
      #     branch: deployment/${{ fromJson(inputs.port_payload).context.runId }}
      #     title: "[Deployment] Add ${{ fromJson(inputs.bucket_name) }} s3 bucket crossplane manifest"
      #     body: |
      #       This PR is automatically generated by Port.
      #       It contains the crossplane manifest for the s3 bucket ${{ fromJson(inputs.bucket_name) }}.

      #       The manifest is generated based on the blueprint: ${{ fromJson(inputs.port_payload).context.blueprint }}.

      #       The run id is: ${{ fromJson(inputs.port_payload).context.runId }}.
      #       The run was triggered by: ${{ fromJson(inputs.port_payload).trigger.by.user.email }}.
      #       The run was triggered at: ${{ fromJson(inputs.port_payload).trigger.at }}.
      #       The run was triggered from: ${{ fromJson(inputs.port_payload).trigger.from }}.


      #       - Auto-generated by [port-actions][1] 

      #       [1]: https://app.getport.io/organization/run?runId=${{ fromJson(inputs.port_payload).context.runId }}
      #     labels: |
      #       deployment
      #       automated pr
      #     assignees: ${{ fromJson(inputs.port_payload).trigger.by.user.email }}

      - name: Inform Port about pull request creation status - Success
        if: steps.create-pr.outputs.pull-request-url != ''
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
          logMessage: |
            Pull request created successfully. You can view the pull request [here](${{ steps.create-pr.outputs.pull-request-url }}).


      - name: Inform Port about pull request creation status - Failure
        if: steps.create-pr.outputs.pull-request-url == ''
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
          logMessage: |
            Failed to create pull request. Please check the logs for more details.
