name: Datadog Exporter Workflow

# This workflow is responsible for running Datadog exporter.

on:
  workflow_dispatch:

jobs:
  run-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: port-labs/ocean-sail@v1
        with:
          type: 'linear'
          port_client_id: ${{ secrets.OCEAN__PORT__CLIENT_ID }}
          port_client_secret: ${{ secrets.OCEAN__PORT__CLIENT_SECRET }}
          config: |
            datadog_base_url: https://api.datadoghq.eu          
            datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
            datadog_application_key:  ${{ secrets.DATADOG_APP_KEY }}
