name: Jira Exporter Workflow

# This workflow responsible for running Jira exporter.

on:
  workflow_dispatch:

jobs:
  run-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: port-labs/ocean-sail@v1
        with:
          type: 'jira'
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          config: |
            jira_host: ${{ secrets.JIRA_HOST }}
            atlassian_user_email: ${{ secrets.ATLASSIAN_USER_EMAIL }}
            atlassian_user_token: ${{ secrets.ATLASSIAN_USER_TOKEN }}
