name: Delete/Revert Statuspage Incident Postmortem

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - delete
          - revert
      port_context: # Input for Port context (JSON)
        description: "Port context (JSON format)"
        required: true

env:
  STATUSPAGE_PAGE_ID: ${{ fromJson(inputs.port_context).entity.relations.statuspage }}
  INCIDENT_ID: ${{ fromJson(inputs.port_context).entity.identifier }}


jobs:
  manage_postmortem:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Port (Initial)
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Publishing Statuspage incident postmortem for incident: ${{ fromJson(inputs.port_context).entity.title }}

      - name: Reverse Statuspage Incident Postmortem
        if: ${{ inputs.action == 'revert' }}
        run: |
          curl -X PUT https://api.statuspage.io/v1/pages/${{ env.STATUSPAGE_PAGE_ID }}/incidents/${{ env.INCIDENT_ID }}/postmortem/revert \
            -H 'Authorization: OAuth ${{ secrets.STATUSPAGE_API_KEY }}' \
            -H 'Content-Type: application/json'

      - name: Delete Statuspage Incident Postmortem
        if: ${{ inputs.action == 'delete' }}
        run: |
          curl -X DELETE https://api.statuspage.io/v1/pages/${{ env.STATUSPAGE_PAGE_ID }}/incidents/${{ env.INCIDENT_ID }}/postmortem \
            -H 'Authorization: OAuth ${{ secrets.STATUSPAGE_API_KEY }}' \
            -H 'Content-Type: application/json'

      - name: Notify Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          status: "SUCCESS"
          logMessage: |
            Completed action: ${{ inputs.action }} on Statuspage incident postmortem for incident: ${{ fromJson(inputs.port_context).entity.title }}