name: Merge Pull Request

on: 
    workflow_dispatch:
      inputs:
        port_payload:
          required: true
          description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
          type: string

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        env:
          pr_number: ${{ fromJson(inputs.port_payload).context.entity }}
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/merge"
