name: Nudge Pull Request Reviewers

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string

jobs:
  nudge-pr-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Repository and PR Number
        id: extract_info
        run: |
          link="${{ fromJson(inputs.port_payload).payload.entity.properties.link }}"
          repo_info=$(echo "$link" | sed 's|https://github.com/||' | awk -F'/' '{print $1 "/" $2}')
          pr_number=$(echo "$link" | awk -F'/' '{print $NF}')

          echo "REPO_INFO=$repo_info" >> $GITHUB_ENV
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV

      - name: Get GitHub Pull Request Reviewers
        id: get_reviewers
        uses: LiamPerson/get-reviews-action@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.REPO_INFO }}
          PULL_REQUEST_ID: ${{ env.PR_NUMBER }}

      - name: Send Slack Notification
        env:
          PR_TITLE: ${{ fromJson(inputs.port_payload).payload.entity.title }}
          REVIEWERS: ${{ fromJson(inputs.port_payload).payload.properties.reviewers }}
        run: |
          reviews_json="${{ steps.get_reviewers.outputs.reviews_file_path }}"
          reviewers=$(jq -r '.[].user.login' $reviews_json | sort -u)

          echo "Reviewers: $REVIEWERS"
          port_reviewers=$(echo $REVIEWERS | tr ' ' '\n' | awk '{print "  - " $0}')
          echo "Port Reviewers: $port_reviewers"

          pr_title="${{ fromJson(inputs.port_payload).payload.entity.title }}"
          
          echo "Reviewers: $reviewers"
          
          pr_link="https://github.com/${{ env.REPO_INFO }}/pull/${{ env.PR_NUMBER }}"
          
          # Construct Block Kit message
          message_payload=$(cat <<EOF
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Reminder: Pending Pull Request Review*\nThis PR needs your attention!"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*PR:* [$pr_title]($pr_link) " 
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Reviewers:*\n$reviewers" 
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Port Reviewers:*\n$port_reviewers" 
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Review PR",
                      "emoji": true
                    },
                    "url": "$pr_link" 
                  }
                ]
              }
            ]
          }
          EOF
          )
          
          curl -X POST -H 'Content-type: application/json' --data "$message_payload" ${{ secrets.SLACK_WEBHOOK_URL }}
          

      - name: Notify Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          baseUrl: https://api.getport.io
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
          logMessage: |
            GitHub Action completed!
