name: Resize Autoscaling Group

on: 
  workflow_dispatch:
    inputs:
      asg_name:
        description: 'Name of the Auto Scaling Group'
        required: true
      desired_capacity:
        description: 'New desired capacity'
        required: true
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string

jobs:
  resize-asg:
    runs-on: ubuntu-latest 
    steps:
      - name: Create a log message
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_payload).context.runId}}
          logMessage: Configuring AWS credentials


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Resize Auto Scaling Group
        run: aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${{ github.event.inputs.asg_name }} --desired-capacity ${{ github.event.inputs.desired_capacity }} 
      
      - name: Create a log message
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_payload).context.runId}}
          logMessage: Resized EC2 Auto Scaling Group ${{ github.event.inputs.asg_name }} to ${{ github.event.inputs.desired_capacity }} instances