name: Update Statuspage Incident

on:
  workflow_dispatch:
    inputs:
      incident_id:
        description: 'ID of the Statuspage incident to update'
        required: true
      new_incident_status:
        description: 'New status of the incident'
        required: true
      update_message:
        description: 'message to include in the update'
        required: false
      affected_components:
        description: 'List of components affected by the incident'
        required: false
      port_context: # Input for Port context (JSON)
        description: "Port context (JSON format)"
        required: true


env:
  STATUSPAGE_PAGE_ID: ${{ fromJson(inputs.port_context).entity.relations.statuspage || secrets.STATUSPAGE_PAGE_ID }}
  INCIDENT_ID: ${{ fromJson(inputs.port_context).entity.identifier }}

jobs:
  update_incident:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Port (Initial)
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Creating Statuspage incident: ${{ inputs.incident_id }} in status page: ${{ fromJson(inputs.port_context).entity.title }}

      - name: Update Statuspage Incident
        run: |
          curl -X PUT https://api.statuspage.io/v1/pages/${{ env.STATUSPAGE_PAGE_ID }}/incidents/${{ env.INCIDENT_ID }} \
            -H 'Authorization: OAuth ${{ secrets.STATUSPAGE_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{
              "incident": {
                "body": "${{ inputs.update_message }}",
                "status": "${{ inputs.new_incident_status }}",
                "component_ids": ${{ inputs.affected_components }},
                "metadata": {
                  "port": {
                    "runId": "${{ fromJson(inputs.port_context).runId }}",
                    "trigger": "${{ fromJson(inputs.port_context).trigger }}"
                  }
                }
              }
            }'

      - name: Notify Port about Update
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          status: "SUCCESS"
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Updated Statuspage incident (${{ inputs.incident_id }}) to status: ${{ inputs.new_incident_status }}
